import { vars } from 'nativewind';
import { colors } from './colors';

export const themes = {
  light: vars({
    '--color-primary': colors.light.primary,
    '--color-primary-50': colors.light['primary-50'],
    '--color-primary-100': colors.light['primary-100'],
    '--color-primary-200': colors.light['primary-200'],
    '--color-primary-300': colors.light['primary-300'],
    '--color-primary-400': colors.light['primary-400'],
    '--color-primary-500': colors.light['primary-500'],
    '--color-primary-600': colors.light['primary-600'],
    '--color-primary-700': colors.light['primary-700'],
    '--color-primary-800': colors.light['primary-800'],
    '--color-primary-900': colors.light['primary-900'],
    '--color-primary-950': colors.light['primary-950'],
    '--color-background': colors.light.background,
    '--color-background-300': colors.light['background-300'],
    '--color-background-400': colors.light['background-400'],
    '--color-background-500': colors.light['background-500'],
    '--color-background-600': colors.light['background-600'],
    '--color-background-700': colors.light['background-700'],
    '--color-text': colors.light.text,
    '--color-text-500': colors.light['text-500'],
    '--color-text-600': colors.light['text-600'],
    '--color-text-700': colors.light['text-700'],
    '--color-error': colors.light.error,
    '--color-error-50': colors.light['error-50'],
    '--color-error-100': colors.light['error-100'],
    '--color-error-200': colors.light['error-200'],
    '--color-error-300': colors.light['error-300'],
    '--color-error-400': colors.light['error-400'],
    '--color-error-500': colors.light['error-500'],
    '--color-error-600': colors.light['error-600'],
    '--color-error-700': colors.light['error-700'],
    '--color-error-800': colors.light['error-800'],
    '--color-error-900': colors.light['error-900'],
    '--color-error-950': colors.light['error-950'],
  }),
  dark: vars({
    '--color-primary': colors.dark.primary,
    '--color-primary-50': colors.dark['primary-50'],
    '--color-primary-100': colors.dark['primary-100'],
    '--color-primary-200': colors.dark['primary-200'],
    '--color-primary-300': colors.dark['primary-300'],
    '--color-primary-400': colors.dark['primary-400'],
    '--color-primary-500': colors.dark['primary-500'],
    '--color-primary-600': colors.dark['primary-600'],
    '--color-primary-700': colors.dark['primary-700'],
    '--color-primary-800': colors.dark['primary-800'],
    '--color-primary-900': colors.dark['primary-900'],
    '--color-primary-950': colors.dark['primary-950'],
    '--color-background': colors.dark.background,
    '--color-background-300': colors.dark['background-300'],
    '--color-background-400': colors.dark['background-400'],
    '--color-background-500': colors.dark['background-500'],
    '--color-background-600': colors.dark['background-600'],
    '--color-background-700': colors.dark['background-700'],
    '--color-text': colors.dark.text,
    '--color-text-500': colors.dark['text-500'],
    '--color-text-600': colors.dark['text-600'],
    '--color-text-700': colors.dark['text-700'],
    '--color-error': colors.dark.error,
    '--color-error-50': colors.dark['error-50'],
    '--color-error-100': colors.dark['error-100'],
    '--color-error-200': colors.dark['error-200'],
    '--color-error-300': colors.dark['error-300'],
    '--color-error-400': colors.dark['error-400'],
    '--color-error-500': colors.dark['error-500'],
    '--color-error-600': colors.dark['error-600'],
    '--color-error-700': colors.dark['error-700'],
    '--color-error-800': colors.dark['error-800'],
    '--color-error-900': colors.dark['error-900'],
    '--color-error-950': colors.dark['error-950'],
  }),
};
